# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projecttechrelationship'),
        ('books', '0003_booktechrelationship'),
        ('lessons', '0002_lessontechrelationship'),
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='books',
            field=models.ManyToManyField(through='books.BookTechRelationship', to='books.Book'),
        ),
        migrations.AddField(
            model_name='tech',
            name='lessons',
            field=models.ManyToManyField(through='lessons.LessonTechRelationship', to='lessons.Lesson'),
        ),
        migrations.AddField(
            model_name='tech',
            name='projects',
            field=models.ManyToManyField(through='projects.ProjectTechRelationship', to='projects.Project'),
        ),
    ]
