# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:51
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0004_techindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techrelatedvideolink',
            name='url',
        ),
        migrations.AddField(
            model_name='techrelatedvideolink',
            name='video',
            field=wagtail.wagtailcore.fields.StreamField([(b'video', wagtail.wagtailembeds.blocks.EmbedBlock())], blank=True),
        ),
    ]
