# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:02
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0005_auto_20170823_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='techrelatedarticlelink',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
