# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0003_techstudentrelationship'),
        ('students', '0003_student_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='techs',
            field=models.ManyToManyField(through='techs.TechStudentRelationship', to='techs.Tech'),
        ),
    ]
