# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_initial'),
        ('projects', '0002_projectstudentrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTechRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='projects.Project')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.Tech')),
            ],
        ),
    ]
